export const CategoryData = [
  {
    path: "victus",
    type: "kompyuter",
    title: "Victus",
    image: require("../assets/images/logo/vic.png"),
    width: 24,
  },
  {
    path: "hp",
    type: "kompyuter",
    title: "HP Laptop",
    image: require("@/assets/images/logo/hp.jpeg"),
    width: 40,
  },
  {
    path: "lenovo",
    type: "kompyuter",
    title: "Lenovo",
    image: require("@/assets/images/logo/lonova.webp"),
    width: 40,
  },
  {
    path: "samsung",
    type: "kompyuter",
    title: "Samsung",
    image: require("@/assets/images/logo/samsung.webp"),
    width: 40,
  },
  {
    path: "asus",
    type: "kompyuter",
    title: "Asus",
    image: require("@/assets/images/logo/asus.jpg"),
    width: 40,
  },
  {
    path: "mac_book",
    type: "kompyuter",
    title: "MacBook",
    image: require("@/assets/images/logo/mac.png"),
    width: 28,
  },
  {
    path: "acer",
    type: "kompyuter",
    title: "Acer",
    image: require("@/assets/images/logo/acer.png"),
    width: 35,
  },
  {
    path: "iphone",
    title: "iPhone",
    type: "telifon",
    image: require("@/assets/images/logo/mac.png"),
    width: 28,
    left: 5,
  },
  {
    path: "samsung",
    title: "Samsung",
    type: "telifon",
    image: require("@/assets/images/logo/samsung.webp"),
    width: 40,
  },
  {
    path: "xiaomi",
    title: "Xiaomi",
    type: "telifon",
    image: require("@/assets/images/logo/mi.png"),
    width: 40,
  },
  {
    path: "poco",
    title: "Poco",
    type: "telifon",
    image: require("@/assets/images/logo/poco.png"),
    width: 38,
  },
  {
    path: "redmi",
    title: "Redmi",
    type: "telifon",
    image: require("@/assets/images/logo/mi.png"),
    width: 40,
  },
  {
    path: "vivo",
    title: "Vivo",
    type: "telifon",
    image: require("@/assets/images/logo/vivo.jpg"),
    width: 40,
  },
  {
    path: "huawei",
    title: "Huawei",
    type: "telifon",
    image: require("@/assets/images/logo/huvavi.png"),
    width: 40,
  },
];

export const Viloyatlar = [
  { value: "Toshkent", label: "Toshkent" },
  { value: "Andijon", label: "Andijon" },
  { value: "Buxoro", label: "Buxoro" },
  { value: "Farg'ona", label: "Farg'ona" },
  { value: "Jizzax", label: "Jizzax" },
  { value: "Xorazm", label: "Xoraz" },
  { value: "Namangan", label: "Namangan" },
  { value: "Navoiy", label: "Navoiy" },
  { value: "Qashqadaryo", label: "Qashqadaryo" },
  { value: "Samarqand", label: "Samarqand" },
  { value: "Sirdaryo", label: "Sirdaryo" },
  { value: "Surxondaryo", label: "Surxondaryo" },
];
